
## 多数据源配置
spring:
  datasource:
    dynamic:
      master:
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3307/spring?characterEncoding=utf8&useSSL=false
      slaves:
        one:
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://45.77.223.114/spring?characterEncoding=utf8&useSSL=false
#        two:
#          username: root
#          password: 123456
#          driver-class-name: com.mysql.jdbc.Driver
#          url: jdbc:mysql://47.100.20.186:3309/spring?characterEncoding=utf8&useSSL=false

## 主从分离配置
sharding:
  jdbc:
    datasource:
      names: ds_master,ds_slave_0,ds_slave_1
      ds_master:
        ...
      ds_slave_0:
        ...
      ds_slave_1:
        ...
    config:
      masterslave:
        load-balance-algorithm-type: round_robin
        name: ds_ms
        master-data-source-name: ds_master
        slave-data-source-names: ds_slave_0,ds_slave_1



Spring:
  datasource:
    #配置监控统计拦截的 filters，去掉后监控界面 sq|将无法统计'wall'用于防火墙
    filters: stat, wall, log4 j
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000

    #打开 PSCache，并且指定每连接 PSCache 的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20

    #通过 connectionProperties 属性来打开 mergeSqI 功能；慢 SQL 记录
    connectionProperties: druid.stat.mergeSql=true;druid.Stat.SlowSqlMillis=5000
    minldle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableldleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileldle: true
    testOnBorrow: false
    testOnReturn: false
